### ISSUE TITLE
Remove curl dependency

### ISSUE THREAD

**Issue by evg82** [egorpugin/tgbot#1]
Im working with your lib, in our project we already use nlohmann json lib, however to avoid external dependencies we are triying to remove curl and use an embedded web client (cpp-httplib).

If this change have interest to you i can prepare a pull request to allow choose curl or "internal" with a define or something.

**Comment by egorpugin** [comment]
I'm ok with that.

1) How do we integrate httplib?
2) Are you using sw build or your own build scripts?
3) Do we need to return back abstract http client like in reo7sp lib?

**Comment by egorpugin** [comment]
Fixed in master.
See providable `http_client` interface.
https://github.com/egorpugin/tgbot/blob/master/include/tgbot/bot.h#L24
