### ISSUE TITLE
LNK1169 in SW building process

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [egorpugin/tgbot#3]
I can't build repo via SW.

Log:
`Starting...
[1602/1603] [tgbot.apitool-1.1.4.6.1].exe
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [tgbot.apitool-1.1.4.6.1].exe
emitter.cpp.e22a782e.obj : error LNK2005: "void __cdecl checkNullptr(void const *)" (?checkNullptr@@YAXPEBX@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "struct _xmlNode * __cdecl findNodeWithText(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?findNodeWithText@@YAPEAU_xmlNode@@PEAU1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getContent(struct _xmlNode *)" (?getContent@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getName(struct _xmlAttr *)" (?getName@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlAttr@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getName(struct _xmlNode *)" (?getName@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "struct _xmlNode * __cdecl getNext(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?getNext@@YAPEAU_xmlNode@@PEAU1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "void __cdecl removeComments(struct _xmlNode *)" (?removeComments@@YAXPEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "void __cdecl removeNode(struct _xmlNode *)" (?removeNode@@YAXPEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
emitter.cpp.e22a782e.obj : error LNK2005: "void __cdecl removeTags(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?removeTags@@YAXPEAU_xmlNode@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "void __cdecl checkNullptr(void const *)" (?checkNullptr@@YAXPEBX@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "struct _xmlNode * __cdecl findNodeWithText(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?findNodeWithText@@YAPEAU_xmlNode@@PEAU1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getContent(struct _xmlNode *)" (?getContent@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getName(struct _xmlAttr *)" (?getName@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlAttr@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl getName(struct _xmlNode *)" (?getName@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "struct _xmlNode * __cdecl getNext(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?getNext@@YAPEAU_xmlNode@@PEAU1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "void __cdecl removeComments(struct _xmlNode *)" (?removeComments@@YAXPEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "void __cdecl removeNode(struct _xmlNode *)" (?removeNode@@YAXPEAU_xmlNode@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
parser.cpp.fb61dbf1.obj : error LNK2005: "void __cdecl removeTags(struct _xmlNode *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?removeTags@@YAXPEAU_xmlNode@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 㦥 ��।���� � api_tool.cpp.400640b1.obj
   ��������� ������⥪� C:/Users/User/useful_lib/.sw/out/780354/tgbot.apitool-1.1.4.6.1.lib � ��ꥪ� C:/Users/User/useful_lib/.sw/out/780354/tgbot.apitool-1.1.4.6.1.exp
C:\Users\User\useful_lib\.sw\out\780354\tgbot.apitool-1.1.4.6.1.exe : fatal error LNK1169: �����㦥� ��������⭮ ��।������� ᨬ��� - ���� ��� �����
command failed: exit code = 1169 (0x491)
Total errors: 1

Finished.`

**Comment by egorpugin** [comment]
Hi, 

Try to re-run command. It should be fixed now.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
It works! Thank you... but I've some more questions and I'll write them in new report.
