### ISSUE TITLE
Is there any "How to ... for dummies"?

### ISSUE THREAD

**Issue by drewaaaaa** [egorpugin/tgbot#4]
I didn't get how to add/compile/install this library to my system. Copy/paste? How to work with SW tool is also unsolvable puzzle for me. Maybe more detailed instruction for use exists?

С другой библиотекой на c++ было проще, там хоть описан процесс установки, но там довольно несвежий API, да и недавно что-то всё навернулось, думаю, куда переезжать, хотел попробовать эту библиотеку-обёртку.

**Comment by egorpugin** [comment]
Вот здесь есть пример.
https://github.com/egorpugin/tgbot/tree/master/examples/report_detection_bot
Добавил ридми.
